name: malwares scanner

on:
  workflow_dispatch:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUP: deepfence
      COMMIT: ${{ github.sha }}
      REPO: demo-app
      DEEPFENCE_CONSOLE_URL: ""
      DEEPFENCE_KEY: ""
    steps:
    - uses: actions/checkout@v2

    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: python-server:${{ github.sha }}

    # Run Deepfence Malware Scanner to check for malwares in image
    - name: Run Deepfence Malware Scanner
      env:
        DEEPFENCE_CONSOLE_URL: ${{ env.DEEPFENCE_CONSOLE_URL }}
        DEEPFENCE_KEY: ${{ env.DEEPFENCE_KEY }}
        FULL_IMAGE_NAME: python-server:${{ github.sha }}
        FAIL_MALWARE_COUNT: 100 # Fail build if number of malwares found is >= this number. Set -1 to pass regardless of malwares.
        FAIL_HIGH_MALWARE_COUNT: 10 # Fail build if number of high malwares found is >= this number. Set -1 to pass regardless of high malwares.
        FAIL_MEDIUM_MALWARE_COUNT: 20 # Fail build if number of medium malwares found is >= this number. Set -1 to pass regardless of medium malwares.
        FAIL_LOW_MALWARE_COUNT: 50 # Fail build if number of low malwares found is >= this number. Set -1 to pass regardless of low malwares.
      run: |
        docker pull deepfenceio/deepfence_malware_scanner_ce:v2
        docker run -i --rm --net=host --privileged=true -v /var/run/docker.sock:/var/run/docker.sock:rw deepfenceio/deepfence_malware_scanner_ce:v2 -image-name "$FULL_IMAGE_NAME -fail-on-count=$FAIL_MALWARE_COUNT -fail-on-high-count=$FAIL_HIGH_MALWARE_COUNT -fail-on-medium-count=$FAIL_MEDIUM_MALWARE_COUNT -fail-on-low-count=$FAIL_LOW_MALWARE_COUNT"

    # # Push to dockerhub
    # - name: Push to Docker Hub
    #   uses: docker/build-push-action@v1
    #   if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    #   with:
    #     username: ${{ secrets.DOCKER_USER }}
    #     password: ${{ secrets.DOCKER_PASS }}
    #     repository: ${{ env.GROUP }}/${{ env.REPO }}
    #     tag_with_ref: true
    #     tag_with_sha: true